import os
from PIL import Image

def generate_icons(source_path, target_dir):
    img = Image.open(source_path)
    if img.mode != 'RGBA':
        img = img.convert('RGBA')

    # PNG icons
    png_icons = {
        "32x32.png": (32, 32),
        "64x64.png": (64, 64),
        "128x128.png": (128, 128),
        "128x128@2x.png": (256, 256),
        "icon.png": (512, 512),
        "Square30x30Logo.png": (30, 30),
        "Square44x44Logo.png": (44, 44),
        "Square71x71Logo.png": (71, 71),
        "Square89x89Logo.png": (89, 89),
        "Square107x107Logo.png": (107, 107),
        "Square142x142Logo.png": (142, 142),
        "Square150x150Logo.png": (150, 150),
        "Square284x284Logo.png": (284, 284),
        "Square310x310Logo.png": (310, 310),
        "StoreLogo.png": (50, 50),
    }

    for name, size in png_icons.items():
        resized = img.resize(size, Image.Resampling.LANCZOS)
        resized.save(os.path.join(target_dir, name))
        print(f"Generated {name} ({size[0]}x{size[1]})")

    # Generate .ico
    ico_sizes = [(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)]
    ico_imgs = [img.resize(size, Image.Resampling.LANCZOS) for size in ico_sizes]
    ico_imgs[0].save(os.path.join(target_dir, "icon.ico"), sizes=ico_sizes)
    print("Generated icon.ico")

    # Generate .icns
    # Pillow doesn't support .icns natively for icons, but let's check.
    # Actually, as of recent versions, it might.
    try:
        icns_sizes = [(16, 16), (32, 32), (64, 64), (128, 128), (256, 256), (512, 512), (1024, 1024)]
        icns_imgs = [img.resize(size, Image.Resampling.LANCZOS) for size in icns_sizes]
        # Ensure larger sizes are present for icns
        icns_imgs[0].save(os.path.join(target_dir, "icon.icns"), sizes=icns_sizes)
        print("Generated icon.icns")
    except Exception as e:
        print(f"Error generating .icns with Pillow: {e}")
        # If Pillow fails for .icns, we might need another way, but Tauri icons usually work better if generated by its CLI.
        # But let's try this first.

if __name__ == "__main__":
    source = "resources/abro_icon.png"
    target = "src-tauri/icons"
    if os.path.exists(source):
        generate_icons(source, target)
    else:
        print(f"Source {source} not found.")
